#flightgoggles_ros_bridge:
    # obstacle_frames: [""]
flightgoggles_uav_dynamics:
    init_pose: [18.5, 6.5, 1.0, 0.0, 0.0, 0.0, 1.0]
    # Uncomment clockscale for manual clock scaling rate.
    # While commented out and use_sim_time=1, FG will auto scale clock
    # for 60hz camera operation.
    # clockscale: 1.0
    ignore_collisions: false
    vehicle_mass: 1.0
    vehicle_inertia_xx: 0.029125
    vehicle_inertia_yy: 0.029125
    vehicle_inertia_zz: 0.055225
    max_prop_speed: 2200.0
    moment_arm: 0.08
    motor_time_constant: 0.02
    motor_rotational_inertia: 6.62e-6
    thrust_coefficient: 6.11e-8
    torque_coefficient: 1.5e-9
    drag_coefficient: 0.1
    aeromoment_coefficient_xx: 0.003
    aeromoment_coefficient_yy: 0.003
    aeromoment_coefficient_zz: 0.003
    moment_process_noise: 1.25e-7
    force_process_noise: 0.0005
    use_ratethrust_controller: true
    use_rungekutta4integrator: false

flightgoggles_imu:
    accelerometer_variance: 0.005
    gyroscope_variance: 0.003
    accelerometer_biasprocess: 1.0e-7
    gyroscope_biasprocess: 1.0e-7
    accelerometer_biasinitvar: 0.0
    gyroscope_biasinitvar: 0.0

flightgoggles_laser:
    rangefinder_variance: 0.009
    rangefinder_max_range: 20.0

flightgoggles_lpf:
    gain_p: 35530.5758439217
    gain_q: 266.572976289502

flightgoggles_pid:
    gain_p_roll: 10.0
    gain_i_roll: 0.0
    gain_d_roll: 0.0
    gain_p_pitch: 10.0
    gain_i_pitch: 0.0
    gain_d_pitch: 0.0
    gain_p_yaw: 10.0
    gain_i_yaw: 0.0
    gain_d_yaw: 0.0
    int_bound_roll: 1000.0
    int_bound_pitch: 1000.0
    int_bound_yaw: 1000.0
    vehicle_inertia_xx: 0.029125
    vehicle_inertia_yy: 0.029125
    vehicle_inertia_zz: 0.055225
    moment_arm: 0.08
    thrust_coefficient: 6.11e-8
    torque_coefficient: 1.5e-9

flightgoggles_ros_bridge:
   # For <= v1.7.1, scene_filename: Butterfly_World, Hazelwood_Loft_Full_Day, Hazelwood_Loft_Full_Night, NYC_Subway, Museum_Day, Museum_Day_Small
   # For >= 2.0.0,  scene_filename: Abandoned_Factory_Morning, Abandoned_Factory_Morning_No_Gates, Abandoned_Factory_Sunset, Abandoned_Factory_Sunset_No_Gates
   scene_filename: Abandoned_Factory_Morning
   image_width: 640
   image_height: 480
   #image_width: 1920
   baseline: 0.32
   collider_radius: 0.15
   framerate: 60
   #world_frame: "world/ned"
